#include "Game/System/WPadRumbleData.hpp"
#include "Game/Util/HashUtil.hpp"
#include <revolution/wpad.h>

static RumblePattern gRumblePatternTable[] = {
    {
        "\x8d\xc5\x8b\xad\x81\x79\x92\xb7\x81\x7a",
        100,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
        },
    },
    {
        "\x8d\xc5\x8b\xad",
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        "\x8b\xad",
        30,
        {
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        "\x92\x86",
        30,
        {
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        "\x8e\xe3",
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        "\x94\xf7\x8e\xe3",
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x83\x58\x83\x8a\x83\x62\x83\x76\x83\x41\x83\x62\x83\x76]",
        25,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x8b\x54\x93\x8a\x82\xb0]",
        10,
        {
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x83\x7a\x83\x62\x83\x70\x81\x5b\x82\xbd\x82\xdf]",
        5,
        {
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x95\xcf\x90\x67]",
        60,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x95\xcf\x90\x67\x89\xf0\x8f\x9c]",
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x82\xb5\x82\xd1\x82\xea]",
        60,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
        },
    },
    {
        "\x83\x7d\x83\x8a\x83\x49[\x82\xc2\x82\xd4\x82\xea]",
        120,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
        },
    },
    {},
};

namespace RumbleData {
    u32 getTableSize() {
        return ARRAY_SIZE(gRumblePatternTable) - 1;
    }

    RumblePattern* getData(u16 index) {
        return &gRumblePatternTable[index];
    }

    const RumblePattern* getPattern(const char* pName) {
        u32 hash = MR::getHashCode(pName);

        for (u16 i = 0; i < getTableSize(); i++) {
            if (getData(i)->mHash == hash) {
                return &gRumblePatternTable[i];
            }
        }

        return nullptr;
    }

    void initHashValue() {
        for (u32 i = 0; i < getTableSize(); i++) {
            RumblePattern* pPattern = getData(i);

            pPattern->mHash = MR::getHashCode(pPattern->mName);
        }
    }

    void checkHashCollision() {
    }
};  // namespace RumbleData
